### ISSUE TITLE
If exif_read_data brings up some error the whole script fails

### ISSUE THREAD

**Issue by 01-Scripts** [bitHugger/MulticolumnGallery#4]
If I have some images with uncorrect EXIF information or some non image files inside the image folder I get the following warnings and the whole gallery fails to load:

<b>Warning</b>:  exif_read_data(2011-08-28_ac00360370.jpg): Incorrect APP1 Exif Identifier Code in <b>***\php\Image.php</b> on line <b>124</b>
<b>Warning</b>:  exif_read_data(.gitignore): File not supported in <b>***\php\Image.php</b> on line <b>124</b>
<b>Warning</b>:  Division by zero in <b>***\php\Column.php</b> on line <b>144</b><br />

**Comment by 01-Scripts** [comment]
Problem is still open. I sent you an example image and provided a patch ( #5 ).

**Comment by bitHugger** [comment]
solved by merge #63b6c7a
