### ISSUE TITLE
Gallery doesn't work if image folder is some levels above the app root

### ISSUE THREAD

**Issue by 01-Scripts** [bitHugger/MulticolumnGallery#6]
Application doesen't work with the following folder structure:

![schnappschuss_011015_103209_pm](https://cloud.githubusercontent.com/assets/200336/5693340/7e5ccdc4-9918-11e4-8a52-f8c68ad235a2.jpg)

I tried to use these settings:
    "your_image_directory_path": "../img/gallery/",
    "your_thumbnail_directory_path": "../img/gallery_tmb/",
But that didn't work.

**Comment by bitHugger** [comment]
solved in f7fde3c
